### ISSUE TITLE
index out of range [0] with length 0

### ISSUE THREAD

**Issue by 89z** [Kunal-Diwan/go-get-youtube#1]
~~~
PS D:\Desktop\go-get-youtube-Library> .\go-get-youtube -id va1oiojnGrA
Hold on ...
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Kunal-Diwan/go-get-youtube/youtube.parseMeta({0xc0000aa090, 0xb}, {0x0?, 0xc00008d5f0?})
        D:/Desktop/go-get-youtube-Library/youtube/yotube.go:640 +0x805
github.com/Kunal-Diwan/go-get-youtube/youtube.Get({0xc0000aa090, 0xb})
        D:/Desktop/go-get-youtube-Library/youtube/yotube.go:393 +0xc5
main.main()
        D:/Desktop/go-get-youtube-Library/ytdownload.go:101 +0x227
~~~

**Comment by poka-IT** [comment]
Same problem here.

**Comment by thiagowaib** [comment]
I'm having the same issue, originated from the `youtube.Get()` method.
